typedef unsigned char uint8_t;
typedef unsigned int uint32_t;
typedef uint32_t size_t;

extern char __bss[], __bss_end[], __stack_top[];

void *memset(void *buf, char c, size_t n) {
  uint8_t *p = (uint8_t *) buf; // cast to uint8_t pointer
  while(n--) 
    *p++ = c; // set each byte to c (kernel_main sets 0)
  return buf;
}

void kernel_main(void) {
  // initialize bss: uninitialzed data section defined in linker script
  memset(__bss, 0, (size_t) __bss_end - (size_t) __bss);
  // infinite loop (end of kernel)
  for (;;);
}

__attribute__((section(".text.boot"))) // place this function in .text.boot section
__attribute__((naked)) // naked attribute: no prologue/epilogue generated by compiler
void boot(void) {
  // set stack pointer, and jump to kernel_main
  __asm__ __volatile__ ( // volatile attribute: prevent compiler from optimizing this code (like -O0)
    "mv sp, %[stack_top]\n"
    "j kernel_main\n"
    :
    : [stack_top] "r" (__stack_top)
  );
}
